### ISSUE TITLE
Issue on page /short_vignettes/initpops_vignette.html

### ISSUE THREAD

**Issue by hyanwong** [molpopgen/fwdpy11#1137]
https://molpopgen.github.io/fwdpy11/short_vignettes/initpops_vignette.html#initializing-with-ancestry-from-msprime says "Note: The details of this section will change once msprime 1.0 is released.". It's been released now, so I guess this note should be changed?

**Comment by molpopgen** [comment]
Thanks.  Looking over the vignette, none of the code needs to change!  That comment is definitely out of date.

**Comment by molpopgen** [comment]
FYI: this issue will not automatically close until the fix in #1138 is merged into `main`.  Unlike tskit, we collect new features in the `dev` branch and are in the middle of a cycle of alpha releases from that branch.
