### ISSUE TITLE
Save genetic_value_fxn in ModelParams?

### ISSUE THREAD

**Issue by vancleve** [molpopgen/fwdpy11#130]
https://github.com/molpopgen/fwdpy11/blob/7045e3b39aa797c84898404fbb73194a0660425b/fwdpy11/wright_fisher.py#L58

By invoking `make_gvalue` above and not saving the result in `ModelParams`, python cannot talk to the stateful fitness function instantiation. For example, if I want a recorder to save values from variables in the fitness object, I can't do that.

Maybe save the actual fitness object in the ModelParams?

**Comment by molpopgen** [comment]
There are a few different issues with this idea.

1. The genetic value objects don't seem pickle-able.  (I've not been able to figure out a method to ensure that).  This matters for a variety of reasons.

2. I do not see a use case for getting anything other than genetic value, noise, and fitness out of these objects.  These values are already recorded as diploid metadata, and thus available to a recorder.

3. A recorder would not see the genetic value object anyways.   A recorder must be convertible to `std::function<void(const poptype &)>`.  So, the best case is you'd have access to the very last set of data. 

What is the use case for needing to see data other than what is already being recorded?  I usually consider the internal state to be the object's own business and that what really matters is its output.  When is that not the case?

**Comment by molpopgen** [comment]
See #132 re: the complexity of pickling these types.  The simpler set of class structures, etc., in 0.2.0 makes pickling challenging at best.

**Comment by vancleve** [comment]
offline chat about new design of fwdpy11 I think resolves this.
