### ISSUE TITLE
Requesting a simple example with a Wright-Fisher population

### ISSUE THREAD

**Issue by olavurmortensen** [molpopgen/fwdpy11#325]
It would like to request a simple Wright-Fisher example in `fwdpy11`. This would be very useful as it would serve as a gentle introduction to the simulator, and at the same time illustrate how to make a simulation without selection.

I found the `diploid_ind.cc` example on the `fwdpp` repo:

> https://github.com/molpopgen/fwdpp/blob/master/examples/diploid_ind.cc

I find it difficult to grasp the code in this example, as I'm completely new to `fwdpp`/`fwdpy11`. Perhaps one *should* learn `fwdpp` to be able to properly use `fwdpy11`, this is not entirely clear to me.

As a side note, in the meantime, I will be trying to write the `diploid_ind.cc` example in `fwdpy11`, so if anyone has any suggestions I would greatly appreciate that.

**Comment by molpopgen** [comment]
The manual contains many examples.  For example, here is the background selection model: https://fwdpy11.readthedocs.io/en/stable/examples/bgs.html

The W-F simulation is implemented with tree sequences as `fwdpy11.evolvets`  and without tree sequences as `fwdpy11.evolve`.

As for the C++ details, the link you provide is about as simple as it gets and each step is commented.  The final step of printing a sample to screen has been removed b/c libsequence is evolving quite a bit right now.  A development branch of fwdpp has a detailed example of simulation with tree sequences using fwdpp's implementation of those methods: https://github.com/molpopgen/fwdpp/blob/tree_seq_example_programs/examples/wfts_integration_test.cc

fwdpy11 is intended for running simulations in Python.  The back-end in C++ using fwdpp and pybind11.  fwdpy11 is much more complex in some ways than fwdpp b/c it is providing more features.  It is simpler than fwdpp in others, though, because some of the abstractions are made concrete.

**Comment by molpopgen** [comment]
This file may be a better example for sims w/tree sequences.  It is also from the dev branch referred to previously: https://github.com/molpopgen/fwdpp/blob/tree_seq_example_programs/examples/wfts_overlapping_generations.cc

**Comment by olavurmortensen** [comment]
> The manual contains many examples. For example, here is the background selection model: https://fwdpy11.readthedocs.io/en/stable/examples/bgs.html

That's true. But the reason I'm interested in the `diploid_ind.cc` example is because I want to simulate neutral sites.

> The W-F simulation is implemented with tree sequences as fwdpy11.evolvets and without tree sequences as fwdpy11.evolve.

Can only find a function called `fwdpy11.evolve_genomes`, which does what you describe.

> As for the C++ details, the link you provide is about as simple as it gets and each step is commented. The final step of printing a sample to screen has been removed b/c libsequence is evolving quite a bit right now. A development branch of fwdpp has a detailed example of simulation with tree sequences using fwdpp's implementation of those methods: https://github.com/molpopgen/fwdpp/blob/tree_seq_example_programs/examples/wfts_integration_test.cc
>
> fwdpy11 is intended for running simulations in Python. The back-end in C++ using fwdpp and pybind11. fwdpy11 is much more complex in some ways than fwdpp b/c it is providing more features. It is simpler than fwdpp in others, though, because some of the abstractions are made concrete.

Thanks for clearing that up.

I just need to read more in the `fwdpy11` documentation and figure out how to do simulations without selection.

**Comment by molpopgen** [comment]
> > The manual contains many examples. For example, here is the background selection model: https://fwdpy11.readthedocs.io/en/stable/examples/bgs.html
> 
> That's true. But the reason I'm interested in the `diploid_ind.cc` example is because I want to simulate neutral sites.

No selection is just a different set of parameters.  For the BGS example, setting U to zero results in no selected mutations.  After the sim, neutral mutations are added to the tree sequence.

> 
> > The W-F simulation is implemented with tree sequences as fwdpy11.evolvets and without tree sequences as fwdpy11.evolve.
> 
> Can only find a function called `fwdpy11.evolve_genomes`, which does what you describe.

Yes, that's the one.  It is so rarely used that I got the name wrong.

> 
> > As for the C++ details, the link you provide is about as simple as it gets and each step is commented. The final step of printing a sample to screen has been removed b/c libsequence is evolving quite a bit right now. A development branch of fwdpp has a detailed example of simulation with tree sequences using fwdpp's implementation of those methods: https://github.com/molpopgen/fwdpp/blob/tree_seq_example_programs/examples/wfts_integration_test.cc
> > fwdpy11 is intended for running simulations in Python. The back-end in C++ using fwdpp and pybind11. fwdpy11 is much more complex in some ways than fwdpp b/c it is providing more features. It is simpler than fwdpp in others, though, because some of the abstractions are made concrete.
> 
> Thanks for clearing that up.
> 
> I just need to read more in the `fwdpy11` documentation and figure out how to do simulations without selection.

I describe that above.  However, if you are interested mostly in neutral models, a forward simulation may not be the tool you want.  You may prefer [msprime](http://msprime.readthedocs.io).

**Comment by molpopgen** [comment]
One thing to keep in mind: the docs are almost entirely geared towards sims w/tree sequences.  The function to simulate genomes has much worse algorithmic behavior.  See [the tree sequence simplification paper](https://doi.org/10.1371/journal.pcbi.1006581) for details.

**Comment by olavurmortensen** [comment]
> No selection is just a different set of parameters. For the BGS example, setting U to zero results in no selected mutations. After the sim, neutral mutations are added to the tree sequence.

Cool, will check that out.

> I describe that above. However, if you are interested mostly in neutral models, a forward simulation may not be the tool you want. You may prefer msprime.

I'm working with msprime as well, but want to be able to make forwards-simulations as well, particularly because I'm mostly interested in very recent demography.

> One thing to keep in mind: the docs are almost entirely geared towards sims w/tree sequences. The function to simulate genomes has much worse algorithmic behavior. See the tree sequence simplification paper for details.

Been meaning to read that paper. It keeps popping up in unconnected ways, seems like the universe is telling me to read it. The msprime tutorial has an example where it uses some forward-time simulation algorithm from this paper and finishes the simulation with the coalescent. I'm wondering if I this is a better avenue for me than using `fwdpy11`.

Anyway, you can close this issue since it probably isn't relevant.

Thank you for the help. Can I send you an email or something if I have more specific questions at a later stage? Promise to have more concise and researched questions then :)

**Comment by molpopgen** [comment]
> Been meaning to read that paper. It keeps popping up in unconnected ways, seems like the universe is telling me to read it. The msprime tutorial has an example where it uses some forward-time simulation algorithm from this paper and finishes the simulation with the coalescent. I'm wondering if I this is a better avenue for me than using `fwdpy11`.

Depends what the goals are.  Being interested in recent demography shouldn't affect the forward-vs-backward choice.  Selection should.  Just keep in mind that if you want to simulate longer genomic regions, then you'll want the newer discrete-time WF model in msprime.  A paper describing that method is [here](https://www.biorxiv.org/content/10.1101/674440v1).  Not sure if it is out in a journal yet, but I know it is somewhere in the review process if not.

**Comment by molpopgen** [comment]
> Thank you for the help. Can I send you an email or something if I have more specific questions at a later stage? Promise to have more concise and researched questions then :)

Sure, my email address is easily discoverable.
