### ISSUE TITLE
Consider removing '-g0' from default build

### ISSUE THREAD

**Issue by jeromekelleher** [molpopgen/fwdpy11#41]
I've been trying to do some profiling, and the lack of debug symbols is causing some unexpected havoc with Linux perf. I don't really want to enable the assertions, since I would like to get an accurate measurement of the code in production.

Unless the debugging symbols make the shared objects very large indeed, it would be better for me if they were left in by default. That way I can watch a live execution with 'perf top' and see exactly where the time is being spent.

**Comment by molpopgen** [comment]
This is fixed via the commit to fwdpy11/dev referenced above.  You now have --debug vs --assert as setup.py options.

dev is compatible w/master, and master == the current release.

**Comment by jeromekelleher** [comment]
Perfect, thanks.
