### ISSUE TITLE
Allow genetic value types to be implemented in Python.

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#460]
Use the trampoline method: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python

**Comment by evodevosys** [comment]
I've been trying to understand how to write custom genetic value class definitions in python and came across this issue. Does this open issue mean that it is not yet possible? If it is currently possible, when you have time could you post a short example of one? It could be something simple even if not biologically realistic - for example the diploid genetic value would be the largest of the mutational effects.  Seeing the python code for that or something else would help me understand what is required for a new genetic value type to work.  Thanks!

**Comment by molpopgen** [comment]
It is not yet possible, for a few reasons.  To add a new model, new c++
code is needed.  The test suite has several examples, such as
https://www.github.com/molpopgen/fwdpy11/tree/master/tests%2Fcustom_additive.cc
.

**Comment by evodevosys** [comment]
thanks - I'll try it with c++

**Comment by molpopgen** [comment]
The examples folder has a standalone example of building such a thing. The
builds in the test suite work differently.

**Comment by evodevosys** [comment]
do you have a link handy for the example in the examples folder?  I'm not sure which file you mean - I don't see any c++ files

**Comment by molpopgen** [comment]
https://github.com/molpopgen/fwdpy11/tree/24bd7567887feb880d51dd93b6803f55920cf6e1/examples/plugin

**Comment by molpopgen** [comment]
pybind/pyind11#1049 is relevant

**Comment by molpopgen** [comment]
@evodevosys -- I am making some progress on this.  I'm experimenting with the "genetic value to fitness" classes first, as they're less complex.

**Comment by molpopgen** [comment]
@evodevosys -- this will be out in 0.9.0, perhaps as the only feature difference from the 0.8.x releases.  It'll be "soon".  I've done 2 of the 3 required tasks.

**Comment by molpopgen** [comment]
Support for this is now merged into master.  Docs are being written in #553.

@evodevosys -- in the meantime, see `tests/pygss.py`, `tests/pynoise.py` and `tests/pyadditive.py` for concrete examples used in the test suite.

**Comment by evodevosys** [comment]
@molpopgen Thanks for adding this. I'm looking forward to trying it out.

**Comment by molpopgen** [comment]
@evodevosys I'm delaying a stable release a bit in order to think about the API some more.

The docs for the current API are available in the dev branch of the manual: https://fwdpy11.readthedocs.io/en/dev/pages/advancedtopics.html#writing-genetic-value-classes-in-python

Some details there are out of date and others are subject to change until 0.9.0 hits.
