### ISSUE TITLE
channel for users questions

### ISSUE THREAD

**Issue by JoseBlanca** [molpopgen/fwdpy11#897]
Hi:

I've just found out about your project and I'd like to use it to teach population genetics. However, as a new user I have some questions, but I don't find in the documentation which is the preferred channel to ask them. They are not issues, but doubts that I have not cleared in my mind after following your tutorials. Where should I ask them?
Best,

Jose Blanca

**Comment by molpopgen** [comment]
The Discussions feature is enabled for this repository.  You can ask questions over there.

**Comment by JoseBlanca** [comment]
Thank you!
