### ISSUE TITLE
Non-integer sizes when importing demes models

### ISSUE THREAD

**Issue by apragsdale** [molpopgen/fwdpy11#929]
If a demographic model `g` has non-integer population sizes (which is very possible, especially when it's the output of an inferred model from dadi or moments), `fwdpy11.discrete_demography.from_demes(g)` will be happy to create a `fwdpy11` demographic model with non-integer sizes, which will fail when used in simulations.

Possible solution: when importing `from_demes()`, round population sizes to ints (either np.round or floor).

**Comment by molpopgen** [comment]
Thanks @apragsdale.  A couple of questions:

* Can you post a YAML file + some minimal Python code that triggers this?  That would be helpful for testing.
* Do you have a full traceback for the exception?

**Comment by apragsdale** [comment]
This example:
```Python
import demes
import fwdpy11

b = demes.Builder()
b.add_deme("A", epochs=[{"start_size": 100.5}])
g = b.resolve()
print("Demes model:", end="\n\n")
print(g)

demog = fwdpy11.discrete_demography.from_demes(g)
print("fwdpy11 model:", end="\n\n")
print(demog.asblack())

L = 1
r = 0

# initialize the ancestral population
print("Initial sizes =", demog.metadata["initial_sizes"])
initial_sizes = [
    demog.metadata["initial_sizes"][i]
    for i in sorted(demog.metadata["initial_sizes"].keys())
]
pop = fwdpy11.DiploidPopulation(initial_sizes, L)
```

results in this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Project/MXB/fwdpy11_demes_error.py:23, in <module>

File ~/miniconda3/envs/fwdpy11/lib/python3.9/site-packages/fwdpy11/_types/diploid_population.py:50, in DiploidPopulation.__init__(self, N, length, ll_pop)
     42 def __init__(
     43     self,
     44     N: Union[int, List[int]],
   (...)
     47     ll_pop: Optional[ll_DiploidPopulation] = None,
     48 ):
     49     if ll_pop is None:
---> 50         super(DiploidPopulation, self).__init__(N, length)
     51     else:
     52         super(DiploidPopulation, self).__init__(ll_pop)

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. fwdpy11._fwdpy11.ll_DiploidPopulation(N: int, length: float)
    2. fwdpy11._fwdpy11.ll_DiploidPopulation(demesizes: List[int], length: float)
    3. fwdpy11._fwdpy11.ll_DiploidPopulation(arg0: fwdpy11._fwdpy11.ll_DiploidPopulation)

Invoked with: [100.5], 1
```

**Comment by molpopgen** [comment]
That is not the same error as from the screen shot sent via Slack.

The error from the example above is because no instances of SetDemeSize are ever created, leaving it up to the DiploidPopulation class to catch the error upon initialization.

The error reported via Slack is from a different class:

![Image from iOS](https://user-images.githubusercontent.com/6416159/164556826-3b3015f4-fec1-4a9b-8fbe-0d8972828943.jpg)
:

**Comment by apragsdale** [comment]
What about this? Looks like there is an error in calling `fwdpy11.discrete_demography.from_demes(g)` in this case.

```Python
import demes
import fwdpy11

b = demes.Builder()
b.add_deme("A", epochs=[{"start_size": 100}])
b.add_deme("B", ancestors=["A"], start_time=10, epochs=[{"start_size": 100.5}])
g = b.resolve()
print("Demes model:", end="\n\n")
print(g)

demog = fwdpy11.discrete_demography.from_demes(g)
```

**Comment by molpopgen** [comment]
> What about this? Looks like there is an error in calling `fwdpy11.discrete_demography.from_demes(g)` in this case.
> 
> ```python
> import demes
> import fwdpy11
> 
> b = demes.Builder()
> b.add_deme("A", epochs=[{"start_size": 100}])
> b.add_deme("B", ancestors=["A"], start_time=10, epochs=[{"start_size": 100.5}])
> g = b.resolve()
> print("Demes model:", end="\n\n")
> print(g)
> 
> demog = fwdpy11.discrete_demography.from_demes(g)
> ```

Yep, that does it -- the Python `SetDemeSize` is catching the bad input.

**Comment by molpopgen** [comment]
It looks like there are two separate things not being handled (see comments below):

* Deme sizes changes are not being rounded.
* The start size for an epoch is not being rounded.

Does this sound right @apragsdale ?

**Comment by apragsdale** [comment]
That sounds right - I think it would all get handled if we just make sure that we round at the first time we see any deme size at any point in an epoch.

Related - we should double check the behavior when times are are non-integer (I know we've looked at it, but just to confirm that's all ok)

**Comment by molpopgen** [comment]
> Related - we should double check the behavior when times are are non-integer (I know we've looked at it, but just to confirm that's all ok)

You mean on the demes side, or here, when we round?
