### ISSUE TITLE
macOS wheels work flow

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#940]
The step where wheels are downloaded as artifacts and installed seems to have a path problem.  For example, from the 0.18.0 builds:

![image](https://user-images.githubusercontent.com/6416159/170572437-26840380-6d27-488d-857e-d637de7a16d0.png)

For Linux for the same release:

![image](https://user-images.githubusercontent.com/6416159/170572599-17b1c0c5-c4b3-450d-9343-657e76ab3e3a.png)

**Comment by benjeffery** [comment]
I#ve found you have to use `--no-index` to `pip` or the test passes as it downloads the missing wheel.

**Comment by molpopgen** [comment]
But then the dependencies aren't there and the work flow fails?

**Comment by molpopgen** [comment]
The msprime work flow has this odd step: before testing the whl file, you install msprime using pip and then uninstall.  That brings in the dependencies for a no index install of the wheel.  Here, it triggers a rebuild of the package from source, which should not be necessary.  (It would also take > 10 minutes on a macOS runner.)

**Comment by benjeffery** [comment]
Yeah good point - I think there is a way to only get the deps with pip. Need to try that.

**Comment by molpopgen** [comment]
> Yeah good point - I think there is a way to only get the deps with pip. Need to try that.

I think I have to "fake" it a bit -- have the action checkout the repo and then maybe just install the dev dependencies.  That's a bit heavy, but should get around the problem.

**Comment by molpopgen** [comment]
On linux, a command like this works after manually installing dependencies from the `requirements/development.txt`:

```sh
python -m pip install fwdpy11 --no-index --pre --only-binary fwdpy11 -f dist
```
