### ISSUE TITLE
Multiple populations

### ISSUE THREAD

**Issue by arundurvasula** [molpopgen/fwdpy11#99]
Hi Kevin!

We are thinking about using fwdpy11 for some forward simulations of Neanderthal demography. I was wondering if there is support for multiple populations with migration? I saw that it's on the long term todo (http://fwdpy11.readthedocs.io/en/dev/pages/todo.html), but Jeff mentioned there may be something on a dev branch that supports this.

Thanks!
Arun

**Comment by molpopgen** [comment]
Hi Arun,

"Neanderthal" demography is what we are working on right now.  @DL42 is working out a simulation along these lines, integrating the ideas from our recent work on tree sequences in forward simulations.

More general support for multiple populations is coming "soon" (famous last words...), but a more direct incorporation of tree sequences is the first priority.

**Comment by arundurvasula** [comment]
Thanks Kevin!
